///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Demo1
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ConnectSuccessful recording.
    /// </summary>
    [TestModule("338cb4df-a9f9-44be-9cca-8acad7024cfc", ModuleType.Recording, 1)]
    public partial class ConnectSuccessful : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Demo1Repository repository.
        /// </summary>
        public static Demo1Repository repo = Demo1Repository.Instance;

        static ConnectSuccessful instance = new ConnectSuccessful();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ConnectSuccessful()
        {
            var_LinkServer = "D:\\Form KMS\\ClientServer-master\\ClientServer-master\\SERVER\\ServerTest\\bin\\Debug\\ServerTest.exe";
            var_LinkClient = "D:\\Form KMS\\ClientServer-master\\ClientServer-master\\CLIENT\\ClientTest\\bin\\Debug\\ClientTest.exe";
            var_IPServer = "";
            var_ConnectSuccessful = "is connecting with you";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ConnectSuccessful Instance
        {
            get { return instance; }
        }

#region Variables

        string _var_LinkServer;

        /// <summary>
        /// Gets or sets the value of variable var_LinkServer.
        /// </summary>
        [TestVariable("de8fa027-ef45-42ff-b621-54d22b0e94f4")]
        public string var_LinkServer
        {
            get { return _var_LinkServer; }
            set { _var_LinkServer = value; }
        }

        string _var_LinkClient;

        /// <summary>
        /// Gets or sets the value of variable var_LinkClient.
        /// </summary>
        [TestVariable("e9b78944-b7b0-437e-9744-f5979c404811")]
        public string var_LinkClient
        {
            get { return _var_LinkClient; }
            set { _var_LinkClient = value; }
        }

        string _var_IPServer;

        /// <summary>
        /// Gets or sets the value of variable var_IPServer.
        /// </summary>
        [TestVariable("1e11d2ed-902c-46b6-ac15-ae3e72a533a2")]
        public string var_IPServer
        {
            get { return _var_IPServer; }
            set { _var_IPServer = value; }
        }

        string _var_ConnectSuccessful;

        /// <summary>
        /// Gets or sets the value of variable var_ConnectSuccessful.
        /// </summary>
        [TestVariable("6463e68e-f3b2-46f4-acc1-71c6636ce1cb")]
        public string var_ConnectSuccessful
        {
            get { return _var_ConnectSuccessful; }
            set { _var_ConnectSuccessful = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.6")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.6")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.0;

            Init();

            // Run Server
            Report.Log(ReportLevel.Info, "Application", "Run Server\r\nRun application with file name from variable $var_LinkServer with arguments '' in normal mode.", new RecordItemIndex(0));
            Host.Local.RunApplication(var_LinkServer, "", "D:\\Form KMS\\ClientServer-master\\ClientServer-master\\SERVER\\ServerTest\\bin\\Debug", false);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'Text' from item 'ServerSide.TxtIPServer' and assigning its value to variable 'var_IPServer'.", repo.ServerSide.TxtIPServerInfo, new RecordItemIndex(1));
            var_IPServer = repo.ServerSide.TxtIPServer.Element.GetAttributeValueText("Text");
            Delay.Milliseconds(0);
            
            // Run Client
            Report.Log(ReportLevel.Info, "Application", "Run Client\r\nRun application with file name from variable $var_LinkClient with arguments '' in normal mode.", new RecordItemIndex(2));
            Host.Local.RunApplication(var_LinkClient, "", "D:\\Form KMS\\ClientServer-master\\ClientServer-master\\CLIENT\\ClientTest\\bin\\Debug", false);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$var_IPServer' with focus on 'ClientSide.TxtIPAddress'.", repo.ClientSide.TxtIPAddressInfo, new RecordItemIndex(3));
            repo.ClientSide.TxtIPAddress.PressKeys(var_IPServer);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ClientSide.BtnConnect' at Center.", repo.ClientSide.BtnConnectInfo, new RecordItemIndex(4));
            repo.ClientSide.BtnConnect.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeContains (Text>$var_ConnectSuccessful) on item 'ClientSide.TxtChatScreen'.", repo.ClientSide.TxtChatScreenInfo, new RecordItemIndex(5));
            Validate.Attribute(repo.ClientSide.TxtChatScreenInfo, "Text", new Regex(Regex.Escape(var_ConnectSuccessful)));
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Application", "Killing application containing item 'ServerSide'.", repo.ServerSide.SelfInfo, new RecordItemIndex(6));
            Host.Local.KillApplication(repo.ServerSide.Self);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Application", "Killing application containing item 'ClientSide'.", repo.ClientSide.SelfInfo, new RecordItemIndex(7));
            Host.Local.KillApplication(repo.ClientSide.Self);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
