///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Demo1
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the Demo1Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.6")]
    [RepositoryFolder("ded4aa9c-34c5-405c-81f3-68ac8d976552")]
    public partial class Demo1Repository : RepoGenBaseFolder
    {
        static Demo1Repository instance = new Demo1Repository();
        Demo1RepositoryFolders.ServerSideAppFolder _serverside;
        Demo1RepositoryFolders.ClientSideAppFolder _clientside;
        Demo1RepositoryFolders.ErrorAppFolder _error;

        /// <summary>
        /// Gets the singleton class instance representing the Demo1Repository element repository.
        /// </summary>
        [RepositoryFolder("ded4aa9c-34c5-405c-81f3-68ac8d976552")]
        public static Demo1Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public Demo1Repository() 
            : base("Demo1Repository", "/", null, 0, false, "ded4aa9c-34c5-405c-81f3-68ac8d976552", ".\\RepositoryImages\\Demo1Repositoryded4aa9c.rximgres")
        {
            _serverside = new Demo1RepositoryFolders.ServerSideAppFolder(this);
            _clientside = new Demo1RepositoryFolders.ClientSideAppFolder(this);
            _error = new Demo1RepositoryFolders.ErrorAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("ded4aa9c-34c5-405c-81f3-68ac8d976552")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ServerSide folder.
        /// </summary>
        [RepositoryFolder("39fe45d1-9017-42c5-9647-834a554cede2")]
        public virtual Demo1RepositoryFolders.ServerSideAppFolder ServerSide
        {
            get { return _serverside; }
        }

        /// <summary>
        /// The ClientSide folder.
        /// </summary>
        [RepositoryFolder("b232837e-b23e-4241-99ea-7130de03415a")]
        public virtual Demo1RepositoryFolders.ClientSideAppFolder ClientSide
        {
            get { return _clientside; }
        }

        /// <summary>
        /// The Error folder.
        /// </summary>
        [RepositoryFolder("7300c5da-5810-4308-8452-057828ec1fa3")]
        public virtual Demo1RepositoryFolders.ErrorAppFolder Error
        {
            get { return _error; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.6")]
    public partial class Demo1RepositoryFolders
    {
        /// <summary>
        /// The ServerSideAppFolder folder.
        /// </summary>
        [RepositoryFolder("39fe45d1-9017-42c5-9647-834a554cede2")]
        public partial class ServerSideAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _txtipserverInfo;
            RepoItemInfo _txtmessageInfo;
            RepoItemInfo _btnsendInfo;
            RepoItemInfo _txtchatscreenInfo;

            /// <summary>
            /// Creates a new ServerSide  folder.
            /// </summary>
            public ServerSideAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ServerSide", "/form[@controlname='ServerSide']", parentFolder, 30000, null, true, "39fe45d1-9017-42c5-9647-834a554cede2", "")
            {
                _txtipserverInfo = new RepoItemInfo(this, "TxtIPServer", "text[@controlname='txt_IPServer']", 30000, null, "0300e711-cd5b-4084-b109-29b1d22d4d58");
                _txtmessageInfo = new RepoItemInfo(this, "TxtMessage", "text[@controlname='txtMessage']", 30000, null, "632ce384-83c5-49e2-868e-2d6c5b17fdd4");
                _btnsendInfo = new RepoItemInfo(this, "BtnSend", "button[@controlname='btnSend']", 30000, null, "eccad40c-42ee-498b-888f-462ec7df365b");
                _txtchatscreenInfo = new RepoItemInfo(this, "TxtChatScreen", "text[@controlname='txtChatScreen']", 30000, null, "35040e31-a67d-486f-a43f-63233e5c2746");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("39fe45d1-9017-42c5-9647-834a554cede2")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("39fe45d1-9017-42c5-9647-834a554cede2")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The TxtIPServer item.
            /// </summary>
            [RepositoryItem("0300e711-cd5b-4084-b109-29b1d22d4d58")]
            public virtual Ranorex.Text TxtIPServer
            {
                get
                {
                    return _txtipserverInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TxtIPServer item info.
            /// </summary>
            [RepositoryItemInfo("0300e711-cd5b-4084-b109-29b1d22d4d58")]
            public virtual RepoItemInfo TxtIPServerInfo
            {
                get
                {
                    return _txtipserverInfo;
                }
            }

            /// <summary>
            /// The TxtMessage item.
            /// </summary>
            [RepositoryItem("632ce384-83c5-49e2-868e-2d6c5b17fdd4")]
            public virtual Ranorex.Text TxtMessage
            {
                get
                {
                    return _txtmessageInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TxtMessage item info.
            /// </summary>
            [RepositoryItemInfo("632ce384-83c5-49e2-868e-2d6c5b17fdd4")]
            public virtual RepoItemInfo TxtMessageInfo
            {
                get
                {
                    return _txtmessageInfo;
                }
            }

            /// <summary>
            /// The BtnSend item.
            /// </summary>
            [RepositoryItem("eccad40c-42ee-498b-888f-462ec7df365b")]
            public virtual Ranorex.Button BtnSend
            {
                get
                {
                    return _btnsendInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BtnSend item info.
            /// </summary>
            [RepositoryItemInfo("eccad40c-42ee-498b-888f-462ec7df365b")]
            public virtual RepoItemInfo BtnSendInfo
            {
                get
                {
                    return _btnsendInfo;
                }
            }

            /// <summary>
            /// The TxtChatScreen item.
            /// </summary>
            [RepositoryItem("35040e31-a67d-486f-a43f-63233e5c2746")]
            public virtual Ranorex.Text TxtChatScreen
            {
                get
                {
                    return _txtchatscreenInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TxtChatScreen item info.
            /// </summary>
            [RepositoryItemInfo("35040e31-a67d-486f-a43f-63233e5c2746")]
            public virtual RepoItemInfo TxtChatScreenInfo
            {
                get
                {
                    return _txtchatscreenInfo;
                }
            }
        }

        /// <summary>
        /// The ClientSideAppFolder folder.
        /// </summary>
        [RepositoryFolder("b232837e-b23e-4241-99ea-7130de03415a")]
        public partial class ClientSideAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _txtipaddressInfo;
            RepoItemInfo _btnconnectInfo;
            RepoItemInfo _btndisconnectInfo;
            RepoItemInfo _btnsendInfo;
            RepoItemInfo _txtmessageInfo;
            RepoItemInfo _txtchatscreenInfo;

            /// <summary>
            /// Creates a new ClientSide  folder.
            /// </summary>
            public ClientSideAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ClientSide", "/form[@controlname='ClientSide']", parentFolder, 30000, null, true, "b232837e-b23e-4241-99ea-7130de03415a", "")
            {
                _txtipaddressInfo = new RepoItemInfo(this, "TxtIPAddress", "text[@controlname='txtIPAddress']", 30000, null, "b3f96c30-23d9-4f94-a9f7-5e2d85466101");
                _btnconnectInfo = new RepoItemInfo(this, "BtnConnect", "button[@controlname='btnConnect']", 30000, null, "8d734e14-6976-4af7-a33c-9a98ecb33b7c");
                _btndisconnectInfo = new RepoItemInfo(this, "BtnDisconnect", "button[@controlname='btnDisconnect']", 30000, null, "86e28131-88b1-4a46-a23e-40a983dba049");
                _btnsendInfo = new RepoItemInfo(this, "BtnSend", "button[@controlname='btnSend']", 30000, null, "c5b9cef5-31a1-4870-92d0-3e8aedd66b9e");
                _txtmessageInfo = new RepoItemInfo(this, "TxtMessage", "text[@controlname='txtMessage']", 30000, null, "a07df338-4cd9-4083-80aa-964829132705");
                _txtchatscreenInfo = new RepoItemInfo(this, "TxtChatScreen", "text[@controlname='txtChatScreen']", 30000, null, "2a6e1b84-1634-4fed-8688-bd008a6d6893");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("b232837e-b23e-4241-99ea-7130de03415a")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("b232837e-b23e-4241-99ea-7130de03415a")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The TxtIPAddress item.
            /// </summary>
            [RepositoryItem("b3f96c30-23d9-4f94-a9f7-5e2d85466101")]
            public virtual Ranorex.Text TxtIPAddress
            {
                get
                {
                    return _txtipaddressInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TxtIPAddress item info.
            /// </summary>
            [RepositoryItemInfo("b3f96c30-23d9-4f94-a9f7-5e2d85466101")]
            public virtual RepoItemInfo TxtIPAddressInfo
            {
                get
                {
                    return _txtipaddressInfo;
                }
            }

            /// <summary>
            /// The BtnConnect item.
            /// </summary>
            [RepositoryItem("8d734e14-6976-4af7-a33c-9a98ecb33b7c")]
            public virtual Ranorex.Button BtnConnect
            {
                get
                {
                    return _btnconnectInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BtnConnect item info.
            /// </summary>
            [RepositoryItemInfo("8d734e14-6976-4af7-a33c-9a98ecb33b7c")]
            public virtual RepoItemInfo BtnConnectInfo
            {
                get
                {
                    return _btnconnectInfo;
                }
            }

            /// <summary>
            /// The BtnDisconnect item.
            /// </summary>
            [RepositoryItem("86e28131-88b1-4a46-a23e-40a983dba049")]
            public virtual Ranorex.Button BtnDisconnect
            {
                get
                {
                    return _btndisconnectInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BtnDisconnect item info.
            /// </summary>
            [RepositoryItemInfo("86e28131-88b1-4a46-a23e-40a983dba049")]
            public virtual RepoItemInfo BtnDisconnectInfo
            {
                get
                {
                    return _btndisconnectInfo;
                }
            }

            /// <summary>
            /// The BtnSend item.
            /// </summary>
            [RepositoryItem("c5b9cef5-31a1-4870-92d0-3e8aedd66b9e")]
            public virtual Ranorex.Button BtnSend
            {
                get
                {
                    return _btnsendInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BtnSend item info.
            /// </summary>
            [RepositoryItemInfo("c5b9cef5-31a1-4870-92d0-3e8aedd66b9e")]
            public virtual RepoItemInfo BtnSendInfo
            {
                get
                {
                    return _btnsendInfo;
                }
            }

            /// <summary>
            /// The TxtMessage item.
            /// </summary>
            [RepositoryItem("a07df338-4cd9-4083-80aa-964829132705")]
            public virtual Ranorex.Text TxtMessage
            {
                get
                {
                    return _txtmessageInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TxtMessage item info.
            /// </summary>
            [RepositoryItemInfo("a07df338-4cd9-4083-80aa-964829132705")]
            public virtual RepoItemInfo TxtMessageInfo
            {
                get
                {
                    return _txtmessageInfo;
                }
            }

            /// <summary>
            /// The TxtChatScreen item.
            /// </summary>
            [RepositoryItem("2a6e1b84-1634-4fed-8688-bd008a6d6893")]
            public virtual Ranorex.Text TxtChatScreen
            {
                get
                {
                    return _txtchatscreenInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TxtChatScreen item info.
            /// </summary>
            [RepositoryItemInfo("2a6e1b84-1634-4fed-8688-bd008a6d6893")]
            public virtual RepoItemInfo TxtChatScreenInfo
            {
                get
                {
                    return _txtchatscreenInfo;
                }
            }
        }

        /// <summary>
        /// The ErrorAppFolder folder.
        /// </summary>
        [RepositoryFolder("7300c5da-5810-4308-8452-057828ec1fa3")]
        public partial class ErrorAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _text65535Info;
            RepoItemInfo _buttonokInfo;

            /// <summary>
            /// Creates a new Error  folder.
            /// </summary>
            public ErrorAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Error", "/form[@title='Error']", parentFolder, 30000, null, true, "7300c5da-5810-4308-8452-057828ec1fa3", "")
            {
                _text65535Info = new RepoItemInfo(this, "Text65535", "text[@controlid='65535']", 30000, null, "1f734c86-02cd-4f9e-afbf-6e6c7e6611bb");
                _buttonokInfo = new RepoItemInfo(this, "ButtonOK", "button[@text='OK']", 30000, null, "fee9e1f4-7521-4055-b24c-3a80853ab49e");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("7300c5da-5810-4308-8452-057828ec1fa3")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("7300c5da-5810-4308-8452-057828ec1fa3")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Text65535 item.
            /// </summary>
            [RepositoryItem("1f734c86-02cd-4f9e-afbf-6e6c7e6611bb")]
            public virtual Ranorex.Text Text65535
            {
                get
                {
                    return _text65535Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text65535 item info.
            /// </summary>
            [RepositoryItemInfo("1f734c86-02cd-4f9e-afbf-6e6c7e6611bb")]
            public virtual RepoItemInfo Text65535Info
            {
                get
                {
                    return _text65535Info;
                }
            }

            /// <summary>
            /// The ButtonOK item.
            /// </summary>
            [RepositoryItem("fee9e1f4-7521-4055-b24c-3a80853ab49e")]
            public virtual Ranorex.Button ButtonOK
            {
                get
                {
                    return _buttonokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonOK item info.
            /// </summary>
            [RepositoryItemInfo("fee9e1f4-7521-4055-b24c-3a80853ab49e")]
            public virtual RepoItemInfo ButtonOKInfo
            {
                get
                {
                    return _buttonokInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}